version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfiles/debug.Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: betterbookmarks-service
