# Setting the name effectively sets the Build.BuildNumber variable
# Older doc on version number details: https://github.com/MicrosoftDocs/vsts-docs/blob/e5d4e6f62d381a0d78b2c3dba7ffeedcf25be73a/docs/pipelines/build/options.md
name: 1.1.0$(Rev:.r)

trigger:
    branches:
        include:
        - master
    paths:
        include:
        - func/*

pr:
    branches:
        include:
        - master
    paths:
        include:
        - func/*

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

# Be sure that you have the 'coverlet.msbuild' package added to your unit test project for code coverage to work
- script: docker build -f func/Dockerfile.build --build-arg VERSION=$(Build.BuildNumber) --build-arg BUILDCONFIG=$(buildConfiguration) -t $(dockerId)/dotnetcore-build:$(Build.BuildNumber) .
  displayName: 'Performing Docker build and test'

# Extract test results and publish output from the build container
- script: |
    docker run --name dotnetcoreapp --rm -d $(dockerId)/dotnetcore-build:$(Build.BuildNumber)
    docker cp dotnetcoreapp:/app/BetterBookmarks.Functions.UnitTests/testresults $(System.DefaultWorkingDirectory)/testresults
    docker cp dotnetcoreapp:/out $(System.DefaultWorkingDirectory)/app
    docker stop dotnetcoreapp
  displayName: 'Extract test results and publish bits from build container'

# Publish Test Results to Azure Pipelines/TFS
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'testresults/*.trx' 
    # searchFolder: 'func/test-results' # Optional
    mergeTestResults: true # Optional
    failTaskOnFailedTests: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional

# Publish Code Coverage Results to Azure Pipelines/TFS
- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: 'testresults/coverage/coverage.cobertura.xml'

# Stage package for artifact creation
- script: |
    cp $(System.DefaultWorkingDirectory)/app/package.zip $(Build.ArtifactStagingDirectory)/package.zip
  displayName: 'Stage package for artifact creation'

# Publish build artifacts to Azure Pipelines/TFS
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

- task: AzureFunctionApp@1
  displayName: Azure Function App Deploy
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    azureSubscription: outlookAzureSubscriptionConnection
    appType: functionApp
    appName: bbfunction
    package: $(Build.ArtifactStagingDirectory)/package.zip
    appSettings: -DbEndpoint https://betterbookmarks.documents.azure.com:443/ -DatabaseName BetterBookmarks -CollectionName UsersV2 -AuthIssuer https://betterbookmarks.auth0.com/ -AuthAudience https://betterbookmarks.com/api