FROM microsoft/dotnet:2.2-sdk
WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish --output /out/ --configuration Release

EXPOSE 80
CMD ["dotnet", "run", "--urls=http://0.0.0.0:80"]
